[sensors]
sampling_rate = 1000 # Sensor reading timeout. Default: 1000
temperature_barometer_addr = "/dev/i2c-1" # /dev address for the bmp085 sensor
temperature_barometer_name = "Adafruit BMP180" # Name, meta data

[server]
address = "http://localhost:6200" # Eden-server address
secret = "asdf" # JWT secret
